### ISSUE TITLE
Feedback: resources consumption

### ISSUE THREAD

**Issue by Vort** [ortexx/museria-global#5]
I have launched my node with `MUSERIA_STORAGE_DATA_SIZE=10gb` option.
`museria\files` directory started to fill itself with files. That is ok.
But when it was filled at 100%, process did not stopped.
I even not sure if it is slowing down.

So node is constantly downloading and removing files. It is not looking good.
I thought that after a while it will balance itself and process will stop. But no.
Along with several megabytes/sec network usage, client also uses ~10% of my 4 core CPU.

I see no reason why (equivalently) music storage should empty and refill itself completely every hour or so.

![musres](https://user-images.githubusercontent.com/1242858/78236568-d6005b80-74e2-11ea-84c2-436fab0ee1d9.png)

**Comment by ortexx** [comment]
Node doesn't do that by itself(refilling). Several parsers now grab music from the internet and put it in the storage.  Your storage is limited, it is why you can see the circulation. Now there is more demand for storage than supply.  In the nearest future it is expected behavior. If there were more nodes in the network, the load on each node would decrease. The more songs in the storage the less need for parsing new ones. It is natural.
